<?php

/**
 * @file
 * Contains migrate_nodewords.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_nodewords_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_nodewords module.
    case 'help.page.migrate_nodewords':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Nodewords Migrate') . '</p>';
      return $output;

    default:
  }
}

